#!/usr/bin/env python3

import json
import locale
import sys
from typing import List

JSON_FILE = "./../car_sales.json"
REPORT_FILE = "./../cars.pdf"


def load_data(filename):
    """Loads the contents of filename as a JSON file."""
    with open(filename) as json_file:
        data = json.load(json_file)
    return data


def format_car(car):
    """Given a car dictionary, returns a nicely formatted name."""
    return "{} {} ({})".format(car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
    """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
    max_revenue = {"revenue": 0}
    most_sales = {"total_sales": -1}
    sales_per_year = {}
    for item in data:
        # Calculate the revenue generated by this model (price * total_sales)
        # We need to convert the price from "$1234.56" to 1234.56
        item_price = locale.atof(item["price"].strip("$"))
        item_revenue = item["total_sales"] * item_price
        if item_revenue > max_revenue["revenue"]:
            item["revenue"] = item_revenue
            max_revenue = item
        # TODO: also handle max sales
        if item["total_sales"] > most_sales["total_sales"]:
            most_sales = item
        # TODO: also handle most popular car_year
        update_sales_per_year(item, sales_per_year)

    max_year = max(sales_per_year, key=sales_per_year.get)
    sales = sales_per_year[max_year]

    summary = [
        "The {} generated the most revenue: ${}".format(format_car(max_revenue["car"]), max_revenue["revenue"]),
        f"The {format_car(most_sales['car'])} had the most sales: {most_sales['total_sales']}",
        f"The most popular year was {max_year} with {sales} sales."
    ]

    return summary


def update_sales_per_year(item, sales_per_year):
    year = item["car"]["car_year"]
    if year in sales_per_year.keys():
        sales_per_year[year] += item["total_sales"]
    else:
        sales_per_year[year] = item["total_sales"]


def cars_dict_to_table(car_data):
    """Turns the data in car_data into a list of lists."""
    table_data = [["ID", "Car", "Price", "Total Sales"]]
    for item in car_data:
        table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
    return table_data


def build_additional_info(summary):
    result = ""
    for line in summary:
        result += F'{line}<br/>'

    return result


def build_table_data(summary, data):
    result = []
    table_header: list[str] = ['ID', 'Car', 'Price', 'Total Sales']
    table_body: list[str] = []
    for item in data:
        table_row = []
        table_row.append(item['id'])
        table_row.append(f"{item['car']['car_make']} {item['car']['car_model']} ({item['car']['car_year']})")
        table_row.append(item['price'])
        table_row.append(item['total_sales'])
        table_body.append(table_row)
    table_body.insert(0, table_header)
    result = table_body
    return result


def main(argv):
    """Process the JSON data and generate a full report out of it."""
    json_file, report_file = process_args(argv)

    data = load_data(json_file)
    summary = process_data(data)
    print(summary)

    # TODO: turn this into a PDF report
    title = ""
    generate_pdf_report(report_file, title, build_additional_info(summary), build_table_data(summary, data))

    # TODO: send the PDF report as an email attachment


def process_args(argv):
    json_file = JSON_FILE
    report_file = REPORT_FILE
    if len(argv) > 1:
        json_file = argv[1]
    if len(argv) > 2:
        report_file = argv[2]

    return json_file, report_file


def generate_pdf_report(report_file, title, additional_info, table_data):
    import reports
    reports.generate(report_file, title, additional_info, table_data)


if __name__ == "__main__":
    main(sys.argv)
